name: sportRex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hooks_riverpod: ^2.1.1
  http: ^1.1.0
  flutter_hooks: ^0.18.0
  cupertino_icons: ^1.0.2
  logger:
  flutter_svg: ^1.0.3
  get: ^4.6.6
  lottie: ^2.0.0
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  retrofit: ^4.0.1
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  dio: ^5.0.3
  intl: any
  pretty_dio_logger: ^1.3.1
  flutter_riverpod: ^2.3.0
  flutter_screenutil: ^5.9.3
  barcode_scan2: ^4.2.4
  pin_code_fields: ^8.0.1
  local_auth: ^2.1.6
  image_picker: ^0.8.6+1
  json_annotation: ^4.8.0
  dio_cookie_manager: ^2.1.2
  money_formatter: ^0.0.3
  local_session_timeout: ^1.0.0
  fixed_collections: ^0.5.0-beta
  dropdown_search: ^3.0.0
  gap: ^3.0.1
  qr_flutter: ^4.1.0
  image_fade: ^0.6.2
  carousel_slider: ^4.2.1
  flutter_swiper_null_safety: ^1.0.2
  flutter_displaymode: ^0.4.0
  flutter_custom_tabs: ^1.0.4
  blurrycontainer: ^1.0.2
  fl_chart: 0.36.1
  flutter_switch: ^0.3.2
  flutter_secure_storage: ^6.1.0
  shimmer: ^3.0.0
  ether_dart: ^0.0.1+2
  
  
  #might need this dependencies later 
  # flutter_custom_tabs: ^1.0.4
  # dart_extensions: ^2.2.0
  # image_gallery_saver: ^2.0.3
  # path_provider: ^2.0.12
  # share_plus: ^7.1.0
  # url_launcher: ^6.1.9
  webview_flutter: ^4.4.1


dev_dependencies:
  # integration_test:
  #   sdk: flutter


  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.6
  json_serializable: ^6.1.5
  retrofit_generator: ^6.0.0+1
  mockito: ^5.3.2
  flutter_launcher_icons: ^0.11.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/pngs/sport_rex.png"



flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/pngs/
    - assets/images/icons/pngs/2x/
    - assets/images/icons/pngs/3x/
    - assets/images/icons/svgs/
    - assets/images/pngs/
    - assets/images/pngs/2x/
    - assets/images/pngs/3x/
    - assets/images/svgs/
    - assets/images/gif/
    - assets/json/
    - .env

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/Biome-Regular.ttf
          weight: 100
        - asset: assets/fonts/Biome-Regular.ttf
          weight: 200
        - asset: assets/fonts/Biome-Regular.ttf
          weight: 300
        - asset: assets/fonts/Biome-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Biome-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Biome-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Biome-Bold.ttf
          weight: 700
        - asset: assets/fonts/Biome-Bold.ttf
          weight: 800
        - asset: assets/fonts/Biome-Bold.ttf
          weight: 900